menu:
  #Home: /
  归档: /archives
  标签: /tags
  关于: /about
#rss: /atom.xml

widgets: #配置页脚显示哪些小挂件
  - category
#  - tag
  - tagcloud
  - recent_posts
#  - blogroll

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: xzhspace

google_analytics:
favicon: /favicon.ico

baidu_tongji: true
